[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"
startCommand = "npm run start"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[plugins]]
name = "Postgres"
envs = ["DATABASE_URL"]

[template]
name = "Payload CMS MCP Server"
description = "A specialized MCP server for Payload CMS 3.0 that validates code, generates templates, and scaffolds projects following best practices."
tags = ["nodejs", "express", "payload-cms", "mcp", "ai"]
icon = "https://www.payloadcmsmcp.info/logopayload.png" 